version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb+srv://abdularham689:01xAiJuuv77KikvX@cluster0.k72dk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=your-secret-key
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  default:
    driver: bridge